// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://aaflrqcpyusowtvxmtug.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImFhZmxycWNweXVzb3d0dnhtdHVnIiwicm9sZSI6ImFub24iLCJpYXQiOjE3MzU0NjQzMDgsImV4cCI6MjA1MTA0MDMwOH0.tpvSFlo3-q7UQAlNVJJqnAVUbciBn5CDV7DSAUo25-s";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);